kind: pipeline
name: telegram-notification


steps:
- name: telegram-notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: olyv_ci_bot_token
    to:
      from_secret: olyv_ci_bot_id_chat_core
    message: |
      Build event:: {{build.event}}
      Author name: {{commit.author}}
      Author email: {{commit.email}}
      Repo name: {{repo.name}}
      Branch name: {{commit.branch}}
      Commit message: {{commit.message}}
      Commit hash: {{commit.sha}}
      Build nummber: {{build.number}}
      Start in: {{build.started}}
      Dashboard link: {{build.link}}


trigger:
  event:
  - push
  - pull_request
  - promote
  - rollback
  - tag




---
kind: pipeline
type: docker
name: eslint


steps:
- name: eslint
  image: node:12
  commands:
  - npm i
  - npm run lint



#---
#kind: pipeline
#type: docker
#name: cordova-build-android-stable


#steps:


#trigger:
#  branch:
#  - cordova-build-android-stable




#---
#---
#kind: pipeline
#type: docker
#name: cordova-build-android-release


#steps:


#trigger:
#  branch:
#  - cordova-build-android-release




---
kind: pipeline
name: telegram-notification-finish


steps:
- name: telegram-notification
  image: appleboy/drone-telegram
  settings:
    token: 1421331969:AAFFxYtCvBYaJ6vsNf4KLrY1Jazl6RID4J0
    to: -416411935
    message: |
      {{#success build.status}}
        Build number: {{build.number}}
        Build status: {{build.status}}
        Finish in: {{build.finished}}
      {{else}}
        Build number: {{build.number}}
        Build status: {{build.status}}
        Finish in: {{build.finished}}
        Dashboard link: {{build.link}}
      {{/success}}


trigger:
  status:
  - success
  - failure


depends_on:
- eslint
- cordova-build-android-pretest
- cordova-build-android-test
- cordova-build-android-posttest
#- cordova-build-android-stable
#- cordova-build-android-release
