kind: pipeline
type: docker
name: default


steps:
- name: telegram-notification
  image: appleboy/drone-telegram
  settings:
    token: 1421331969:AAFFxYtCvBYaJ6vsNf4KLrY1Jazl6RID4J0
    to: -416411935
    message: |
      Build event:: {{build.event}}
      Author name: {{commit.author}}
      Author email: {{commit.email}}
      Repo owner: {{repo.owner}}
      Repo name: {{repo.name}}
      Branch name: {{commit.branch}}
      Commit message: {{commit.message}}
      Commit hash: {{commit.sha}}
      Build nummber: {{build.number}}
      Start in: {{build.started}}
      Dashboard link: {{build.link}}


- name: telegram-notification
  image: appleboy/drone-telegram
  settings:
    token: 1421331969:AAFFxYtCvBYaJ6vsNf4KLrY1Jazl6RID4J0
    to: -416411935
    message: |
      {{#success build.status}}
        Build number: {{build.number}}
        Build status: {{build.status}}
        Finish in {{build.finished}}
  when:
    status:
    -failure
    - success


- name: eslint
  image: node:12
  commands:
  - npm i
  - npm run lint


- name: dev
  image: node:12
  commands:
  - npm i
  - npm run dev
  when:
    branch:
    - dev


- name: cordova-build-android-pretest
  image: ravino/cordova-v10-for-android:latest
  commands:
  - npm i
  - cd src-cordova && yes | cordova platforms add android@9.0.0 && cd ../
  - npm run cordova-build-android
  when:
    branch:
    - cordova-build-android-pretest
