kind: pipeline
type: docker
name: default


steps:
- name: telegram-notification
  image: appleboy/drone-telegram
  when:
    event:
    - push
  settings:
    token: 1421331969:AAFFxYtCvBYaJ6vsNf4KLrY1Jazl6RID4J0
    to: -416411935
    message: |
      Type {{build.event}} commit {{commit.message}} by {{commit.author}} from branch {{commit.branch}} of repo {{repo.name}}


#- name: eslint
#  image: node:12
#  commands:
#  - npm i
#  - npm run lint


#- name: dev
#  image: node:12
#  commands:
#  - npm i
#  - npm run dev
#  when:
#    branch:
#    - dev


- name: cordova-build-android-pretest
  image: ravino/cordova-v10-for-android:latest
  commands:
  - npm i
  - cd src-cordova && yes | cordova platforms add android@9.0.0 && cd ../
  - npm run cordova-build-android
  when:
    branch:
    - cordova-build-android-pretest
