kind: pipeline
type: docker
name: default


steps:
#- name: eslint
#  image: node:12
#  commands:
#  - npm i
#  - npm run lint


#- name: dev
#  image: node:12
#  commands:
#  - npm i
#  - npm run dev
#  when:
#    branch:
#    - dev


#- name: cordova-build-android-pretest
#  image: ravino/cordova-v10-for-android:latest
#  commands:
#  - npm i
#  - cd src-cordova && yes | cordova platforms add android@9.0.0 && cd ../
#  - npm run cordova-build-android
#  when:
#    branch:
#    - cordova-build-android-pretest


- name: telegram-notification
  image: appleboy/drone-telegram
  settings:
    token: 1421331969:AAFFxYtCvBYaJ6vsNf4KLrY1Jazl6RID4J0
    to: -416411935
+    message: >
+      {{#push build.event}}
+        Start building {{build.number}} from Author {{commit.author}} | Branch {{commit.branch}} | Commit {{commit.message}} | Repo {{repo.name}}
+      {{/push}}
