kind: pipeline
name: telegram-notification


steps:
- name: telegram-notification
  image: appleboy/drone-telegram
  settings:
    token: 1421331969:AAFFxYtCvBYaJ6vsNf4KLrY1Jazl6RID4J0
    to: -416411935
    message: |
      Build event:: {{build.event}}
      Author name: {{commit.author}}
      Author email: {{commit.email}}
      Repo owner: {{repo.owner}}
      Repo name: {{repo.name}}
      Branch name: {{commit.branch}}
      Commit message: {{commit.message}}
      Commit hash: {{commit.sha}}
      Build nummber: {{build.number}}
      Start in: {{build.started}}
      Dashboard link: {{build.link}}




---
kind: pipeline
type: docker
name: eslint


steps:
- name: eslint
  image: node:12
  commands:
  - npm i
  - npm run lint




---
kind: pipeline
type: docker
name: frontend-dev


steps:
- name: frontend-dev
  image: node:12
  commands:
  - npm i
  - npm run dev
  when:
    branch:
    - frontend-dev



---
kind: pipeline
type: docker
name: cordova-build-android-test


steps:
- name: cordova-build-android-test
  image: ravino/cordova-v10-for-android:latest
  commands:
  - npm i
  - cd src-cordova && yes | cordova platforms add android@9.0.0 && cd ../
  - npm run cordova-build-only-www-android
  - cd ./src-cordova && cordova build --debug android && cd ../
  - cp ./src-cordova/platforms/android/app/build/outputs/apk/debug/app-debug.apk ./Olyv_Unsigned_Debug_Test.apk
  when:
    branch:
    - cordova-build-android-test

- name: telegram-notification-status
  image: appleboy/drone-telegram
  settings:
    token: 1421331969:AAFFxYtCvBYaJ6vsNf4KLrY1Jazl6RID4J0
    to: -416411935
    document: ./Olyv_Unsigned_Debug_Test.apk




---
kind: pipeline
type: docker
name: cordova-build-android-posttest


steps:
- name: cordova-build-android-posttest
  image: ravino/cordova-v10-for-android:latest
  commands:
  - npm i
  - cd src-cordova && yes | cordova platforms add android@9.0.0 && cd ../
  - npm run cordova-build-android
  - cp ./src-cordova/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk ./Olyv_Unsigned_Release_Posttest.apk
  - echo "Sosihui_123" | jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ./Olyv.keystore ./Olyv_Unsigned_Release_Posttest.apk Olyv
  - zipalign -v 4 ./Olyv_Unsigned_Release_Posttest.apk Olyv_Signed_Release_Posttest.apk
  when:
    branch:
    - cordova-build-android-posttest

- name: telegram-notification-status
  image: appleboy/drone-telegram
  settings:
    token: 1421331969:AAFFxYtCvBYaJ6vsNf4KLrY1Jazl6RID4J0
    to: -416411935
    document: ./Olyv_Signed_Release_Posttest.apk




---
kind: pipeline
name: telegram-notification-finish


steps:
- name: telegram-notification
  image: appleboy/drone-telegram
  settings:
    token: 1421331969:AAFFxYtCvBYaJ6vsNf4KLrY1Jazl6RID4J0
    to: -416411935
    message: |
      {{#success build.status}}
        Build number: {{build.number}}
        Build status: {{build.status}}
        Finish in: {{build.finished}}
      {{else}}
        Build number: {{build.number}}
        Build status: {{build.status}}
        Finish in: {{build.finished}}
        Dashboard link: {{build.link}}
      {{/success}}


depends_on:
- eslint
- frontend-dev
- cordova-build-android-test
- cordova-build-android-posttest
